// Code generated by go generate; DO NOT EDIT.
// Generated at 2024-07-30 08:54:03.788693771 +0300 EEST m=+0.101868830
// using data from
// https://statics.tls.security.mozilla.org/server-side-tls-conf.json
package main

import (
	"crypto/tls"
	"fmt"
	"net/http"
	"time"
)

var TLSConfig = &tls.Config{
	MinVersion:               tls.VersionTLS12,
	CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
	PreferServerCipherSuites: true,
	CipherSuites: []uint16{
		tls.TLS_AES_128_GCM_SHA256,
		tls.TLS_AES_256_GCM_SHA384,
		tls.TLS_CHACHA20_POLY1305_SHA256,
	},
}


func getTLSSrv(addr string, port string, cfg *tls.Config, mux *http.ServeMux) *http.Server {
	return &http.Server{
		Addr:              fmt.Sprintf("%s:%s", addr, port),
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       5 * time.Second,
		WriteTimeout:      5 * time.Second,
		MaxHeaderBytes:    8192,
		TLSConfig:         cfg,
		TLSNextProto:      make(map[string]func(*http.Server, *tls.Conn, http.Handler), 0),
	}
}
